network-interfaces examples
C2Devel/terraform-examples pull request #10
Opened 2019-06-11 13:21 UTC by Ubun1

**What this PR does / why we need it**:
new examples with ``aws_network_interface`` resource

**Which issue(s) this PR fixes**:
#9 

**Special notes for your reviewer**:

2019-07-03 15:48 UTC, Sharpeye90 commented
$make init

```
init: required argument missing.
make: *** [Makefile:27: init] Error 1
```

2019-07-10 13:40 UTC, Ubun1 commented
@Sharpeye90 rereview pls

2019-07-11 13:56 UTC, Sharpeye90 requested changes

2019-07-11 13:56 UTC, Sharpeye90 commented on cases/aws_key_pair/main.tf
> +resource "tls_private_key" "ssh" {
А это точно надо в этом PR?

2019-07-11 13:56 UTC, Sharpeye90 commented on main.tf
> -variable "material" {}
А это точно надо в этом PR, а не в https://github.com/C2Devel/terraform-examples/pull/18

2019-07-11 13:56 UTC, Sharpeye90 commented on terraform.tfvars.example
> -material = "<your_public_ssh_key>"
Тоже не про этот PR

2019-07-11 13:56 UTC, Sharpeye90 commented on cases/aws_route/main.tf
> + vpc_id = "${aws_vpc.test_vpc.id}"
Зря пробел убрал

2019-07-11 13:56 UTC, Sharpeye90 commented on cases/aws_instance/main.tf
> +resource "tls_private_key" "ssh" {
Это точно нужно в этом PR?

2019-07-12 09:22 UTC, Sharpeye90 approved these changes

2019-07-12 09:23 UTC, merged