Rename placement group strategy
C2Devel/terraform-examples pull request #4
Opened 2019-03-04 15:06 UTC by Ubun1

**What this PR does / why we need it**:
- rename ```distribute``` -> ```spread``` strategy due to latest croc cloud [release](http://docs.website.cloud.croc.ru/en/api/ec2/placements/CreatePlacementGroup.html)

**Which issue(s) this PR fixes**:
- None

**Special notes for your reviewer**:
- None

2019-03-04 17:59 UTC, pkulev requested changes

2019-03-04 17:59 UTC, pkulev commented on cases/aws_placement_group/main.tf
>    # NOTE: the only supported value for 'strategy' attribute is 'distribute'
Forgot commentary.

2019-03-04 18:01 UTC, pkulev commented
Also check README, https://github.com/C2Devel/terraform-examples/blob/master/cases/aws_placement_group/README.rst

2019-03-04 20:32 UTC, Ubun1 commented on cases/aws_placement_group/main.tf
>    # NOTE: the only supported value for 'strategy' attribute is 'distribute'
thx!

2019-03-07 08:45 UTC, Ubun1 commented
@pkulev more comments ?

2019-03-13 13:27 UTC, pkulev approved these changes
It's OK.

2019-03-15 10:14 UTC, merged