change deprecated variables to support terraform 12
C2Devel/terraform-examples pull request #51
Opened 2020-03-03 09:41 UTC by ancient07

add documentation link for libtool, automake for MacOS

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

2020-03-08 19:09 UTC, Ubun1 requested changes
pls split README updates and .tf files refactoring into different commits.

2020-03-10 06:50 UTC, ancient07 commented
> pls split README updates and .tf files refactoring into different commits.

Done

2020-03-17 18:53 UTC, Ubun1 commented
rebase pls

2020-03-18 14:09 UTC, Ubun1 approved these changes

2020-03-18 14:09 UTC, merged