Add quick start for absolute beginners in Terraform
C2Devel/terraform-examples pull request #69
Opened 2021-11-01 10:56 UTC by Girag

**What this PR does / why we need it**:
Add quick start guide for absolute beginners in Terraform with examples and comments.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

2021-11-01 13:14 UTC, Ubun1 commented
можно было и по коммитам то разбить пр (

2021-11-01 13:15 UTC, Ubun1 commented on README.md
> +<p align="center">If you're a beginner in Terraform it might be better to start with <a href="https://github.com/Girag/terraform-examples/tree/terraform-quick-start/quick_start">quick start for absol
форк указан

2021-11-01 13:20 UTC, Ubun1 commented on quick_start/README.md
> +Для начала потребуется скачать Terraform к себе на компьютер. Он распространяется в форме одного запускаемого файла и существует для различных ОС (поддерживаются Linux/Windows/macOS и не только). Ска
Совершенно точно нужно указать конкретную версию на которой эта инструкция была протестированна

2021-11-01 19:38 UTC, Ubun1 commented on quick_start/README.md
> +Для начала потребуется скачать Terraform к себе на компьютер. Он распространяется в форме одного запускаемого файла и существует для различных ОС (поддерживаются Linux/Windows/macOS и не только). Ска
https://github.com/C2Devel/terraform-examples/pull/67 тут кстати не только прибивали версии самого терраформа но и провайдера к амазону

2021-11-01 19:45 UTC, Ubun1 commented
Вооьще говоря, гайд очень подробный. Что хорошо.

2021-11-01 21:30 UTC, Girag commented
> можно было и по коммитам то разбить пр (

Учту на будущее, спасибо.

2021-11-01 21:31 UTC, Girag commented on README.md
> +<p align="center">If you're a beginner in Terraform it might be better to start with <a href="https://github.com/Girag/terraform-examples/tree/terraform-quick-start/quick_start">quick start for absol
Поправил.

2021-11-01 21:32 UTC, Girag commented on quick_start/README.md
> +Для начала потребуется скачать Terraform к себе на компьютер. Он распространяется в форме одного запускаемого файла и существует для различных ОС (поддерживаются Linux/Windows/macOS и не только). Ска
Согласен, добавил.

2021-11-02 10:12 UTC, Sharpeye90 commented on README.md
> +<p align="center">If you're a beginner in Terraform it might be better to start with <a href="https://github.com/C2Devel/terraform-examples/quick_start">quick start for absolute beginners</a> (in Rus
Кстати говоря, если мы хотим иметь доку и в англ и в русском вариантах, то лучше использовать нашу публичную доку, там есть вариант с переводом через занату.

2021-11-02 11:00 UTC, Sharpeye90 requested changes

2021-11-02 11:00 UTC, Sharpeye90 commented on quick_start/README.md
> +Однажды написав такой код, который сам создаст для вас нужное количество виртуальных машин из подходящих шаблонов, выделит необходимое количество внешних IP-адресов, сконфигурирует группы безопасност
Предлагаю без "Согласитесь", более обездушенную инструкцию.

2021-11-02 11:00 UTC, Sharpeye90 commented on quick_start/README.md
> +Для начала потребуется скачать Terraform к себе на компьютер. Он распространяется в форме одного запускаемого файла и существует для различных ОС (поддерживаются Linux/Windows/macOS и не только). Ска
Вне зависимости от того, перейдем ли мы в публичную доку или нет, думаю стоит дать ссылку на https://docs.cloud.croc.ru/ru/api/tools/terraform.html

2021-11-02 11:00 UTC, Sharpeye90 commented on quick_start/README.md
> +Terraform может работать с разными облачными платформами, сервисами и не только при помощи специальных плагинов, которые принято называть провайдерами. Для работы с Облаком КРОК используется провайде
его API - API Облака КРОК

2021-11-02 11:00 UTC, Sharpeye90 commented on quick_start/README.md
> +  region     = "us-east-1"
Почему us-east-1?

2021-11-02 11:00 UTC, Sharpeye90 commented on quick_start/README.md
> +  default     = "ru-msk-comp1p"
Думаю, это стоит обсудить с службой эксплуатации

2021-11-02 11:00 UTC, Sharpeye90 commented on quick_start/README.md
> +  default     = "cmi-3CF790E9"
Надо быть уверенным, что этот шаблон доступен всем, если так и есть, то ок

2021-11-02 11:00 UTC, Sharpeye90 commented on quick_start/README.md
> +- возможность использовать системы управления версиями, такие как Git, и хранить код в хранилищах кода, таких как GitHub – таким образом всегда можно наглядно проследить все вносимые изменения и при
Предлагаю без примеров, ограничиться только возможностью использования сисемой управления версиями.

2021-11-02 11:17 UTC, Girag commented on README.md
> +<p align="center">If you're a beginner in Terraform it might be better to start with <a href="https://github.com/C2Devel/terraform-examples/quick_start">quick start for absolute beginners</a> (in Rus
Можешь рассказать об этом поподробнее?

2021-11-02 11:18 UTC, Girag commented on quick_start/README.md
> +Однажды написав такой код, который сам создаст для вас нужное количество виртуальных машин из подходящих шаблонов, выделит необходимое количество внешних IP-адресов, сконфигурирует группы безопасност
Окей, убрал.

2021-11-02 11:25 UTC, Girag commented on quick_start/README.md
> +Для начала потребуется скачать Terraform к себе на компьютер. Он распространяется в форме одного запускаемого файла и существует для различных ОС (поддерживаются Linux/Windows/macOS и не только). Ска
На самом деле, по указанной ссылке практически не остаётся уникальной информации, которая бы не была разобрана в написанной инструкции. К тому же ссылка на неё есть в главном README этого репозитория. Ты действительно думаешь, что стоит ещё раз её публиковать?

2021-11-02 11:37 UTC, Girag commented on quick_start/README.md
> +Terraform может работать с разными облачными платформами, сервисами и не только при помощи специальных плагинов, которые принято называть провайдерами. Для работы с Облаком КРОК используется провайде
Специально подбирал слова, чтобы избежать повторений в одном предложений. Не будет ли слишком много "облака КРОК" на единицу текста?

> Для работы с Облаком КРОК используется провайдер AWS, так как API Облака КРОК является AWS-совместимым.

Думаешь, так лучше?

2021-11-02 11:40 UTC, Girag commented on quick_start/README.md
> +  region     = "us-east-1"
Этот регион используется для работы с API Облака КРОК по части взаимодействия с S3 эндпоинтом.

2021-11-02 11:44 UTC, Girag commented on quick_start/README.md
> +  default     = "ru-msk-comp1p"
Обсудить, какую зону доступности использовать по умолчанию? Здесь стоит учесть, что вариант по умолчанию используется только в случае, если пользователь не переопределил значение своим.

2021-11-02 11:44 UTC, Girag commented on quick_start/README.md
> +  default     = "cmi-3CF790E9"
Это стандартный шаблон CentOS 8.2 в Облаке, так что всё ок.

2021-11-02 11:52 UTC, Girag commented on quick_start/README.md
> +- возможность использовать системы управления версиями, такие как Git, и хранить код в хранилищах кода, таких как GitHub – таким образом всегда можно наглядно проследить все вносимые изменения и при
Не совсем понял. Ты предлагаешь привести весь этот блок текста примерно к такому?

> Такой подход к взаимодействию с инфраструктурой принято называть "инфраструктура как код" (Infrastructure as a Code, IaaC) и он позволяет использовать для работы над инфраструктурой системы управления версиями, такие как Git, и хранить код в хранилищах кода, таких как GitHub – таким образом всегда можно наглядно проследить все вносимые изменения и при необходимости откатиться к прошлой рабочей версии кода, а также совместно работать над кодом нескольким разработчикам.

2021-11-03 09:58 UTC, Ubun1 commented
LGTM

2021-11-08 08:33 UTC, Sharpeye90 commented on quick_start/README.md
> +Terraform может работать с разными облачными платформами, сервисами и не только при помощи специальных плагинов, которые принято называть провайдерами. Для работы с Облаком КРОК используется провайде
Я просто прочел "его" = провайдер AWS

2021-11-08 08:35 UTC, Sharpeye90 commented on quick_start/README.md
> +- возможность использовать системы управления версиями, такие как Git, и хранить код в хранилищах кода, таких как GitHub – таким образом всегда можно наглядно проследить все вносимые изменения и при
Нет, я конкретно про блок с GIT. Хотелось бы чтоб было 

- возможность использовать системы управления версиями.

2021-11-08 08:39 UTC, Girag commented on quick_start/README.md
> +Terraform может работать с разными облачными платформами, сервисами и не только при помощи специальных плагинов, которые принято называть провайдерами. Для работы с Облаком КРОК используется провайде
Согласен, может возникнуть такая коллизия. Может тогда "его" заменить на "API Облака"? Чтобы не делать слишком громоздкой конструкцию и не полностью повторяться.

2021-11-08 08:42 UTC, Sharpeye90 commented on quick_start/README.md
> +Terraform может работать с разными облачными платформами, сервисами и не только при помощи специальных плагинов, которые принято называть провайдерами. Для работы с Облаком КРОК используется провайде
Да, давай

2021-11-08 08:43 UTC, Girag commented on quick_start/README.md
> +- возможность использовать системы управления версиями, такие как Git, и хранить код в хранилищах кода, таких как GitHub – таким образом всегда можно наглядно проследить все вносимые изменения и при
Понял, сокращу.

2021-12-27 08:35 UTC, Sharpeye90 approved these changes

2021-12-27 08:35 UTC, merged